---
name: "Build literally nothing"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      remote-execution:
        description: "Configure remote-execution server (requires valid CASD keys)"
        type: boolean
        # default: true
        default: false

jobs:
  build1:
    name: Build 1
    uses: ./.github/workflows/reusable-build.yml
    with:
      remote-execution: ${{ inputs.remote-execution == true }}
