---
name: "Build Bootc Image"
on:
  workflow_call:
    inputs:
      remote-execution:
        description: "Configure remote-execution server (requires valid CASD keys)"
        type: boolean
        default: false

jobs:
  build:
    name: build
    runs-on: ubuntu-26.04
    steps:
      - name: test environment
        env:
          ENV: ${{ inputs.remote-execution }}
        run: |
          echo $ENV
